[package]
name = "bounty_manager"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"