[package]
name = "verity_anonymizer"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
privacy.workspace = true
bounty_manager = { path = "../bounty_manager" }

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"